service: lambda-web
plugins:
  - serverless-offline
  - serverless-api-gateway-caching

custom:
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: true
frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x

  # you can overwrite defaults here
  stage: dev
  region: us-east-1
  

  environment: ${file(./env.yml)}

functions:
  index:
    handler: dulce-web/index.handler
    timeout: 30
    events:
      - http:
          path: view/{resource}
          method: get
          caching:
            enabled: true
      - http:
          path: view/{resource}/{methodName}
          method: get
          caching:
            enabled: true
  assets:
    handler: dulce-web/assets.handler
    timeout: 30
    events:
      - http:
          path: assets/{asset}
          method: get
          caching:
            enabled: true

